### ISSUE TITLE
Herd immunity

### ISSUE THREAD

**Issue by larsfu** [PhillipHow/CovidImpfDeBot#1]
I would love to have some kind of explanation for the herd immunity date in the bot, like the assumed vaccination rate etc.
Thanks for the bot, I love it!

**Comment by PhillipHow** [comment]
As this is the most interesting part of the bot, I will add a section on this on the README soon. I will notify you then :)

**Comment by PhillipHow** [comment]
Adressed in dd0c7c4d1cc9884c8039b8cbe209a11f77ff1455. @larsfu 
If you have additional questions, just open another issue :)
