### ISSUE TITLE
Added first and second doses

### ISSUE THREAD

**Issue by JLammering** [PhillipHow/CovidImpfDeBot#2]
It would be nice if the Bot also lists the total added first and second doses of the last day. It’s interesting because right now many more second doses are distributed than a few weeks ago and this affects the distribution speed of first doses. This data is available on the impfdashboard.

example:

1/2 Dosen: 30,79M (37%) +268K
2/2 Dosen: 9,33M (11,2%) +113K

**Comment by PhillipHow** [comment]
You're right, really good idea! I will tackle this in the next days.

**Comment by PhillipHow** [comment]
Done, will go live tomorrow.
